name: Run linters and tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false --local
          poetry install
      - name: bandit
        run: |
          ./scripts/ci/check-bandit.sh
      - name: black
        run: |
          ./scripts/ci/check-formatting.sh
      - name: mypy
        run: |
          ./scripts/ci/check-types.sh
      - name: pytest
        run: |
          ./scripts/ci/run-tests.sh
